### ISSUE TITLE
Can't pull from registry.redhat.io in builder pod

### ISSUE THREAD

**Issue by nicolaferraro** [openshift/builder#145]
I've a pull secret configured at cluster creation for pulling images from registry.redhat.io. That works fine for running pods, but when I start a build from an image that's hosted on registry.redhat.io the builder pod is unable to pull it:

```
[nferraro@localhost camel-k]$ oc logs camel-k-kit-bpv2ejjrmvh2e42n94pg-1-build
Caching blobs under "/var/cache/blobs".

Pulling image registry.redhat.io/openjdk/openjdk-11-rhel8:1.2 ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
```

Shouldn't pull auth tokens be propagated to builders automatically?

Using OpenShift 4.3.5

**Comment by gabemontero** [comment]
At the moment @nicolaferraro , no, it is not automatic for builds.  We are in the process as I type that of making a set of changes that would allow that.

@openshift/openshift-team-developer-experience 
@ricardomaraschini @dmage @adambkaplan please keep me honest here

In the interim, you should follow the steps at https://docs.openshift.com/container-platform/4.3/builds/creating-build-inputs.html#builds-docker-credentials-private-registries_creating-build-inputs

**Comment by nicolaferraro** [comment]
Thanks @gabemontero, may I have some pointers to the changes you refer to?

**Comment by ricardomaraschini** [comment]
@nicolaferraro https://github.com/openshift/openshift-apiserver/pull/83 and https://github.com/openshift/builder/pull/143

**Comment by nicolaferraro** [comment]
Thanks @ricardomaraschini
