### ISSUE TITLE
Add latest containers/image with the „quay mirror fix“ 

### ISSUE THREAD

**Issue by jomeier** [openshift/builder#219]
Hi,

@nalind could you please create a successor PR for https://github.com/openshift/builder/pull/213

Your PR for containers/image was successfully merged yesterday.

Thanks for all your effort and greetings,

Josef

**Comment by jomeier** [comment]
I think that containers/image v5.10.3 should contain the required fix.

**Comment by nalind** [comment]
The image library's `release-5.10` branch doesn't contain https://github.com/containers/image/pull/1138 yet, but a sufficiently-new commit from the mainline is currently being used in https://github.com/openshift/builder/pull/183.  I've opened https://github.com/containers/image/pull/1162 to cherry pick the changes into the image library's `release-5.10` branch.
