### ISSUE TITLE
Entitled builds broken

### ISSUE THREAD

**Issue by nimasamii** [openshift/builder#227]
Commit 7901cb3961215fcdc5a1bb8572de7aa5f02f56cb breaks entitled builds, because entitlement certificates are no longer passed through to the buildah process.

Host entitlements are linked in /usr/share/rhel/secrets on the build-host, which is mounted as /run/secrets (defined /usr/share/containers/mounts.conf) in the build continer. With the commit above only the rhsm portion is copied to the buildah process, the entitlement certificates are not, which results in failed entitled builds.

**Comment by adambkaplan** [comment]
You are correct - we missed the `etc-pki-entitlement` directory, as can be observed on my Fedora 33 machine:

```
$ ls -al /usr/share/rhel/secrets/
total 12
drwxr-xr-x. 1 root root 68 Dec 31  1969 .
drwxr-xr-x. 1 root root 14 Dec 31  1969 ..
lrwxrwxrwx. 4 root root 20 Oct 30 07:28 etc-pki-entitlement -> /etc/pki/entitlement
lrwxrwxrwx. 4 root root 28 Oct 30 07:28 redhat.repo -> /etc/yum.repos.d/redhat.repo
lrwxrwxrwx. 4 root root  9 Oct 30 07:28 rhsm -> /etc/rhsm

```

I will open up a BZ.

**Comment by adambkaplan** [comment]
Filed bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1940488

I will close this GitHub issue - work will be tracked there.
