### ISSUE TITLE
cpu limits should be detectable during s2i build

### ISSUE THREAD

**Issue by tmds** [openshift/builder#318]
During the s2i build, the cpu limit doesn't ripple down to the build process.

.NET, for example, uses the cpu limit to determine how much things it should build in parallel.
When there is no cpu limit, .NET falls back to use the number of physical cores on the machine.

When the build machine has many cores (e.g. 64 or more), the amount of parallelism may be completely inappropriate. This causes the build to stall, consume massive amounts of memory, and finally crash.

.NET determines the cpu limit by dividing `cfs_quota_us` by `cfs_period_us` and rounding it up.
In the s2i build container, `cfs_quota_us` is `-1`.

cc @bparees @nalind @coreydaley

**Comment by nalind** [comment]
> During the s2i build, the cpu limit doesn't ripple down to the build process.
> 
> .NET, for example, uses the cpu limit to determine how much things it should build in parallel. When there is no cpu limit, .NET falls back to use the number of physical cores on the machine.
> 
> When the build machine has many cores (e.g. 64 or more), the amount of parallelism may be completely inappropriate. This causes the build to stall, consume massive amounts of memory, and finally crash.
> 
> .NET determines the cpu limit by dividing `cfs_quota_us` by `cfs_period_us` and rounding it up. In the s2i build container, `cfs_quota_us` is `-1`.

That's a valid value to find there, if I'm reading [the docs](https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt) right.

Can you share the build config or build spec that triggers this behavior?  Does it include resource requests and/or limits?
