### ISSUE TITLE
registries.conf search override is not used for image pulls

### ISSUE THREAD

**Issue by adambkaplan** [openshift/builder#38]
If `registries.conf` is overrode to use a different search registry, image pulls for docker and source strategy builds continue to use the default `docker.io` search path.

Note - cannot be tested on an OpenShift 4.0 cluster until https://github.com/openshift/origin/pull/21864 lands.

**Comment by bparees** [comment]
were you able to verify the overridden search list is used for anything during the build?  is it used for docker builds?

are you sure the issue isn't that the openshift build process replaced the FROM spec w/ a fully qualified one in the dockerfile before starting the build?

**Comment by adambkaplan** [comment]
> are you sure the issue isn't that the openshift build process replaced the FROM spec w/ a fully qualified one in the dockerfile before starting the build?

Can confirm this is not the case - test build log:
```
I0128 21:10:44.548206       1 builder.go:305] Replacing dockerfile
FROM centos/ruby-22-centos7
...
with:
FROM centos/ruby-22-centos7
...
```

**Comment by adambkaplan** [comment]
> is it used for docker builds?

does not seem to be used for docker strategy builds as well...

**Comment by adambkaplan** [comment]
smh - uncaught typo setting the environment variable.

https://github.com/openshift/origin/blob/6aa1c8c7387e1568d0695e222a6f7bc5516fad4e/pkg/build/controller/strategy/util.go#L388

vs.

https://github.com/openshift/origin/blob/master/pkg/build/util/consts.go#L118
