### ISSUE TITLE
docker.io used as registry of last resort for image pulls

### ISSUE THREAD

**Issue by adambkaplan** [openshift/builder#39]
If an image pull spec does not include a repository, it always defaults to docker.io.
Image pulls should instead respect the search configuration provided in `registries.conf`

**Comment by bparees** [comment]
as @adambkaplan noted elsewhere, we think this is caused by this code which should be removed at this point since buildah itself should be handling the defaulting based on the registries.conf
https://github.com/openshift/builder/blob/master/pkg/build/builder/daemonless.go#L53-L56

**Comment by adambkaplan** [comment]
Related (blocking) issue: https://github.com/containers/image/issues/572

**Comment by adambkaplan** [comment]
> That happens before the search list from registries.conf is used?

My understanding of the flow is:

1. Check if the image exists locally - this uses the search path in `registries.conf`
2. If not local, pull image. This invokes the reference parsing logic. Image is then stored with a fully qualified pull spec (`docker.io/...`).
3. When build is invoked, search path in `registries.conf` is used again. Builds will fail because `docker.io` isn't on the search path, and thereby the local image is ignored because it has the `docker.io` prefix.

**Comment by bparees** [comment]
we always default to docker.io now and do not support custom search lists.
