### ISSUE TITLE
retry image pulls

### ISSUE THREAD

**Issue by bparees** [openshift/builder#45]
we should be retrying image pulls in the same way that we retry image pushes, so we do not fail builds on network flakes.

**Comment by gabemontero** [comment]
See https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/120/pull-ci-openshift-cluster-samples-operator-master-e2e-aws-image-ecosystem/305 and https://github.com/openshift/cluster-samples-operator/pull/120#issuecomment-468446790 for instances in our CI where this might have helped
